# This is a basic workflow to help you get started with Actions

name: API Download

# Controls when the workflow will run
on:
  # Run on schedule every Thursday 13:37
  schedule:
    - cron: '37 13 * * 4'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "download"
  download:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Run downloader script
        run: |
          ./download_races.sh
          ./download_bosses.sh

      - name: Commit and push to repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Auto-update from Github Actions"
          git push origin HEAD:master
